# Site settings
title: Kenneth Yang
email: kennethyang404@gmail.com
description: "Kenneth Yang's Website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: github
    url: http://github.com/kennethyang404
  - title: envelope
    url: mailto:kennethyang404@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Carnegie Mellon University
  - line: Pittsburgh, PA 15213, United States

# Build settings
markdown: kramdown
permalink: pretty
